CREATE TABLE OMS_COMPANY_MEMBER (
    CPN_CD VARCHAR(30) PRIMARY KEY NOT NULL,
    CPN_BIZ_NO VARCHAR(20),
    CPN_ID VARCHAR(20),
    CPN_PW VARCHAR(20),
    CPN_NM VARCHAR(60),
    CEO_NM VARCHAR(40),
    CPN_ADDR VARCHAR(255),
    CPN_IMAGE_URL VARCHAR(200),
    CPN_DESC VARCHAR(200),
    OPN_DT VARCHAR(8),
    CPN_TEL VARCHAR(20),
    CPN_EMAIL VARCHAR(40),
    CPN_STATE VARCHAR(10),
    STATE_MDF_DATE DATE,
    REG_DATE DATE
);

select * from OMS_COMPANY_MEMBER;

drop table OMS_COMPANY_MEMBER;


CREATE SEQUENCE cpn_cd_seq
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;
    
    
 